/*
This file is part of TSODLULS library.

TSODLULS is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TSODLULS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TSODLULS.  If not, see <http://www.gnu.org/licenses/>.

©Copyright 2018-2021 Laurent Lyaudet
*/

//This file was generated by generateCompetitors.php script.



#include "TSODLULS__competitor.h"

#define TSODLULS_STACK_SIZE  (CHAR_BIT * sizeof(size_t))
#define TSODLULS_PUSH(low, high)  ((void) ((top->p_low = (low)), (top->p_high = (high)), ++top))
#define TSODLULS_POP(low, high)  ((void) (--top, (low = top->p_low), (high = top->p_high)))
#define TSODLULS_STACK_NOT_EMPTY  (stack < top)



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 3
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_3_6()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 4
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_4_6()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 5
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_5_6()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 6
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_6_6()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 7
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_7_6()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_1(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_1()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_2(a0,a1,a2)
  size_t TSODLULS_macraff_isize;
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_2()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_3(a0,a1,a2)
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_3()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_4(a0,a1,a2)
  char* TSODLULS_macraff_p_char;
  char* TSODLULS_macraff_p_char_2;
  char* TSODLULS_macraff_p_char_3;
  char TSODLULS_macraff_char;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_4()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_5(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_5()



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
){
  #define TSODLULS_MAX_THRESH 8
  #define TSODLULS_SWAP_VAR(a0,a1,a2) TSODLULS_SWAP_VAR_6(a0,a1,a2)
  size_t TSODLULS_macraff_i_chunk_size = TSODLULS_CHUNK_SIZE_FOR_SWAP_VAR(i_element_size);
  size_t TSODLULS_macraff_isize;
  t_TSODLULS_sizables_union TSODLULS_macraff_sizables_union;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_1;
  t_TSODLULS_sizables_pointers_union TSODLULS_macraff_sizables_pointers_union_2;
  #include "./b/body_TSODLULS_qsort__comparison_callback.c"
  #undef TSODLULS_MAX_THRESH
  #undef TSODLULS_SWAP_VAR
}//end function TSODLULS_qsort__comparison_callback_8_6()




#undef TSODLULS_STACK_SIZE
#undef TSODLULS_PUSH
#undef TSODLULS_POP
#undef TSODLULS_STACK_NOT_EMPTY

