/*
This file is part of TSODLULS library.

TSODLULS is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TSODLULS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TSODLULS.  If not, see <http://www.gnu.org/licenses/>.

©Copyright 2018-2021 Laurent Lyaudet
*/

//This file was generated by generateCompetitors.php script.



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_3_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_4_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_5_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_6_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_7_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_1(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_2(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_3(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_4(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_5(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



/**
 * Sorting functions using a comparison callback for arbitrary data structures.
 * Qsort from glibc with minor modifications.
 */
int TSODLULS_qsort__comparison_callback_8_6(
  void* arr_elements,
  size_t i_number_of_elements,
  size_t i_element_size,
  t_comparison_function fn_comparison
);



