/*
This file is part of TSODLULS library.

TSODLULS is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TSODLULS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TSODLULS.  If not, see <http://www.gnu.org/licenses/>.

©Copyright 2018-2021 Laurent Lyaudet
*/

//This file was generated by generateCompetitors.php script.



#include "TSODLULS__competitor.h"

#define TSODLULS_STACK_SIZE  (CHAR_BIT * sizeof(size_t))
#define TSODLULS_PUSH(low, high)  ((void) ((top->p_low = (low)), (top->p_high = (high)), ++top))
#define TSODLULS_POP(low, high)  ((void) (--top, (low = top->p_low), (high = top->p_high)))
#define TSODLULS_STACK_NOT_EMPTY  (stack < top)



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_1(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 1
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_1()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_2(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 2
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_2()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_3(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 3
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_3()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_4(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 4
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_4()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_5(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 5
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_5()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_6(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 6
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_6()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_7(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 7
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_7()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_8(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 8
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_8()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_9(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 9
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_9()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_10(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 10
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_10()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_11(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 11
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_11()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_12(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 12
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_12()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_13(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 13
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_13()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_14(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 14
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_14()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_15(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 15
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_15()



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_16(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define TSODLULS_MAX_THRESH 16
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
  #undef TSODLULS_MAX_THRESH
}//end function TSODLULS_qsort_inlined__short_16()




#undef TSODLULS_STACK_SIZE
#undef TSODLULS_PUSH
#undef TSODLULS_POP
#undef TSODLULS_STACK_NOT_EMPTY

