/*
This file is part of TSODLULS library.

TSODLULS is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TSODLULS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TSODLULS.  If not, see <http://www.gnu.org/licenses/>.

©Copyright 2018-2020 Laurent Lyaudet
*/

//This file was generated by generateQsortInlined.php script.
#include "TSODLULS__competitor.h"

#define STACK_SIZE  (CHAR_BIT * sizeof(size_t))
#define PUSH(low, high)  ((void) ((top->p_low = (low)), (top->p_high = (high)), ++top))
#define POP(low, high)  ((void) (--top, (low = top->p_low), (high = top->p_high)))
#define STACK_NOT_EMPTY  (stack < top)
#define min(x, y) ((x) < (y) ? (x) : (y))


/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_3(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 3
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_3




/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_4(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 4
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_4




/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_5(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 5
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_5




/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_6(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 6
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_6




/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_7(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 7
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_7




/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_8(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 8
  #include "./b/body_TSODLULS_qsort_inlined__short.c"
}//end function TSODLULS_qsort_inlined__short_8




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_3(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 3
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_3




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_4(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 4
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_4




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_5(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 5
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_5




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_6(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 6
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_6




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_7(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 7
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_7




/**
 * Sorting functions for long nextified strings
 * Qsort from glibc inlined with long cells.
 */
int TSODLULS_qsort_inlined__long_8(
  t_TSODLULS_sort_element* arr_elements,
  size_t i_number_of_elements
){
  #define MAX_THRESH 8
  #include "./b/body_TSODLULS_qsort_inlined__long.c"
}//end function TSODLULS_qsort_inlined__long_8



