/*
This file is part of TSODLULS library.

TSODLULS is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TSODLULS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TSODLULS.  If not, see <http://www.gnu.org/licenses/>.

©Copyright 2018 Laurent Lyaudet
*/

//This file was generated by generateQsortInlined.php script.

/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_3(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_4(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_5(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_6(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_7(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);



/**
 * Sorting functions for short nextified strings
 * Qsort from glibc inlined with short cells.
 */
int TSODLULS_qsort_inlined__short_8(
  t_TSODLULS_sort_element__short* arr_elements,
  size_t i_number_of_elements
);


